// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	NewTaskResponse
	Task
	GetRequest
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NewTaskResponse struct {
	Title   string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Created bool   `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
}

func (m *NewTaskResponse) Reset()                    { *m = NewTaskResponse{} }
func (m *NewTaskResponse) String() string            { return proto1.CompactTextString(m) }
func (*NewTaskResponse) ProtoMessage()               {}
func (*NewTaskResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewTaskResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewTaskResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type Task struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto1.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
	Created bool    `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Task    *Task   `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	Tasks   []*Task `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Response) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto1.RegisterType((*NewTaskResponse)(nil), "proto.NewTaskResponse")
	proto1.RegisterType((*Task)(nil), "proto.Task")
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoTasks service

type TodoTasksClient interface {
	NewTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error)
	GetTasks(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type todoTasksClient struct {
	cc *grpc.ClientConn
}

func NewTodoTasksClient(cc *grpc.ClientConn) TodoTasksClient {
	return &todoTasksClient{cc}
}

func (c *todoTasksClient) NewTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.TodoTasks/NewTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoTasksClient) GetTasks(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.TodoTasks/GetTasks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoTasks service

type TodoTasksServer interface {
	NewTask(context.Context, *Task) (*Response, error)
	GetTasks(context.Context, *GetRequest) (*Response, error)
}

func RegisterTodoTasksServer(s *grpc.Server, srv TodoTasksServer) {
	s.RegisterService(&_TodoTasks_serviceDesc, srv)
}

func _TodoTasks_NewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTasksServer).NewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TodoTasks/NewTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTasksServer).NewTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoTasks_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoTasksServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TodoTasks/GetTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoTasksServer).GetTasks(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoTasks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TodoTasks",
	HandlerType: (*TodoTasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTask",
			Handler:    _TodoTasks_NewTask_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _TodoTasks_GetTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto1.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x24, 0x49, 0x43, 0xd3, 0x09, 0xa2, 0x62, 0xc5, 0xc1, 0xe2, 0x42, 0xf0, 0xa9, 0x5c, 0x2a,
	0x54, 0x5e, 0xc0, 0xa9, 0xb7, 0x1e, 0xac, 0x7e, 0x20, 0xd4, 0x2b, 0xd5, 0x2a, 0xaa, 0x43, 0xbc,
	0x88, 0xef, 0xa3, 0x38, 0x29, 0x0d, 0xa8, 0xa7, 0xd5, 0xcc, 0xec, 0xac, 0x67, 0x0c, 0x88, 0xb7,
	0x7e, 0xd9, 0xb4, 0x5e, 0x3c, 0xe5, 0x71, 0xe8, 0x37, 0xcc, 0x37, 0xfc, 0xbd, 0xad, 0xc3, 0xc1,
	0x70, 0x68, 0xfc, 0x31, 0x30, 0xdd, 0x23, 0x17, 0x27, 0x1f, 0xac, 0x92, 0x2a, 0x59, 0xcc, 0x4c,
	0x0f, 0x48, 0x61, 0xba, 0x6b, 0xb9, 0x16, 0xb6, 0x2a, 0xad, 0x92, 0x45, 0x61, 0x4e, 0x50, 0x6f,
	0x30, 0xe9, 0xfc, 0x74, 0x8b, 0xd4, 0xd9, 0x68, 0xca, 0x4d, 0xea, 0xec, 0xf9, 0x4e, 0x3a, 0xbe,
	0x53, 0xa1, 0xb4, 0x1c, 0x76, 0xad, 0x6b, 0xc4, 0xf9, 0xa3, 0xca, 0xa2, 0x36, 0xa6, 0xf4, 0x0d,
	0xb0, 0x66, 0x31, 0xfc, 0xf9, 0xc5, 0x41, 0xf4, 0x1e, 0xc5, 0x6f, 0xb2, 0x51, 0x86, 0xe4, 0x4f,
	0x06, 0x7a, 0xc4, 0x44, 0xea, 0x70, 0x88, 0x4f, 0x95, 0xab, 0xb2, 0xef, 0xb8, 0x8c, 0xb5, 0xa2,
	0x40, 0x4f, 0xc8, 0xbb, 0x19, 0x54, 0x56, 0x65, 0xff, 0x37, 0x7a, 0x65, 0xb5, 0xc7, 0x6c, 0xeb,
	0xad, 0xef, 0xa8, 0x40, 0xcf, 0x98, 0x0e, 0xff, 0x42, 0xe3, 0xdd, 0x87, 0xf9, 0x00, 0x4e, 0x99,
	0xf4, 0x15, 0xbd, 0xa0, 0x58, 0xb3, 0xf4, 0xb6, 0xbb, 0x41, 0x3e, 0x17, 0xb8, 0xe0, 0x78, 0xbf,
	0x8e, 0xcc, 0xeb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0xff, 0x69, 0xe5, 0x90, 0x01, 0x00,
	0x00,
}
